/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'bollywoodSaree' : null } |
  { 'partyWearSaree' : null } |
  { 'readyToWearSaree' : null };
export interface OrderInquiry {
  'customerName' : string,
  'phoneWhatsapp' : string,
  'productId' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export interface Product {
  'id' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'category' : Category,
  'priceIDR' : bigint,
  'priceUSD' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<OrderInquiry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'submitOrderInquiry' : ActorMethod<
    [string, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];