/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const OrderInquiry = IDL.Record({
  'customerName' : IDL.Text,
  'phoneWhatsapp' : IDL.Text,
  'productId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Category = IDL.Variant({
  'bollywoodSaree' : IDL.Null,
  'partyWearSaree' : IDL.Null,
  'readyToWearSaree' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'priceIDR' : IDL.Nat,
  'priceUSD' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderInquiry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'submitOrderInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const OrderInquiry = IDL.Record({
    'customerName' : IDL.Text,
    'phoneWhatsapp' : IDL.Text,
    'productId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Category = IDL.Variant({
    'bollywoodSaree' : IDL.Null,
    'partyWearSaree' : IDL.Null,
    'readyToWearSaree' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'priceIDR' : IDL.Nat,
    'priceUSD' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderInquiry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitOrderInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };